Algoritmo "Variáveis"
// Disciplina   : [Algoritmos e Lógica de Programação]
// Professor   : Cleison Ferreira de Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bianca Carvalho de Almeida
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo